### ISSUE TITLE
Issue with requests dependency that causes version incompatability

### ISSUE THREAD

**Issue by fgs-dbudwin** [chaoss/grimoirelab-perceval#445] opened 2018-10-17 14:01 UTC
Yesterday, `urllib3` which is a dependency for `requests` updated to [version `1.2.4`](https://github.com/urllib3/urllib3/releases/tag/1.24).  Subsequently, `requests` is pulling this latest version of `urllib3` which breaks their version constraint and leads to the following error:

```
Installed c:\python36\lib\site-packages\urllib3-1.23-py3.6.egg
error: urllib3 1.23 is installed but urllib3<1.23,>=1.21.1 is required by {'requests'}
```

I think until both `urllib3` and `requests` fix the bug on their end, `grimoirelab-perceval` should pin their dependencies in a way that prevents this code from depending on the latest `urllib3`.  The bug for `requests` [can be tracked here](https://github.com/requests/requests/issues/4830).

**Comment by jgbarah** [comment] 2018-10-17 16:21
Thanks for the heads-up!

@sduenas, @valcos, do you think we should release a new pip package for Perceval with those dependencies pinned? I can do it as soon as a decission is made.

**Comment by sduenas** [comment] 2018-10-18 07:38
I've been installing perceval on an empty environment and I didn't find any problem even when it installs `urllib3 1.24`:

```
$ python3 -m venv /tmp/perceval
$ source /tmp/perceval/bin/activate
(perceval) $ pip3 install perceval
Collecting perceval
  Downloading https://files.pythonhosted.org/packages/3a/c6/15f3705bcca9a0ab213e6cfeb8c116f6674f8601e6b4b0ac3df889211f2d/perceval-0.12.0-py3-none-any.whl (172kB)
    100% |████████████████████████████████| 174kB 2.3MB/s 
[...]
Collecting urllib3>=1.22 (from perceval)
Downloading https://files.pythonhosted.org/packages/8c/4b/5cbc4cb46095f369117dcb751821e1bef9dd86a07c968d8757e9204c324c/urllib3-1.24-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 7.2MB/s
[...]
Collecting requests>=2.7.0 (from perceval)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
[...]
Installing collected packages: feedparser, six, python-dateutil, grimoirelab-toolkit, urllib3, dulwich, idna, certifi, chardet, requests, beautifulsoup4, perceval
  Running setup.py install for feedparser ... done
  Running setup.py install for dulwich ... done
Successfully installed beautifulsoup4-4.6.3 certifi-2018.10.15 chardet-3.0.4 dulwich-0.18.6 feedparser-5.2.1 grimoirelab-toolkit-0.1.8 idna-2.7 perceval-0.12.0 python-dateutil-2.7.3 requests-2.19.1 six-1.11.0 urllib3-1.24
```

I also tested it and it worked:
```
(perceval)$ perceval github https://github.com/chaoss/grimoirelab-perceval
```

Not sure if I did something wrong.

**Comment by jgbarah** [comment] 2018-10-18 11:02
You're right, @sduenas. I also tried, in different virtual environments:

```
pip install grimoirelab
```

```
pip install perceval
```

```
pip install urllib3
pip install perceval
```

```
pip install requests
pip install perceval
```

All of them worked...

@fgs-dbudwin, how could we reproduce your problem?

**Comment by vchrombie** [comment] 2021-09-15 15:25
Thanks for opening the issue @fgs-dbudwin.

We have released many versions for perceval thereafter and we couldn't reproduce the issue.

Closing the issue as it doesn't have any recent activity.

**Closed by vchrombie** 2021-09-15 15:25 UTC
