### ISSUE TITLE
Problem resolving github.com

### ISSUE THREAD

**Issue by MehdiGol** [chaoss/grimoirelab-perceval#442] opened 2018-10-08 20:56 UTC
I'm trying to use Perceval to retrieve commit data from github.com but the code is throwing this exception

> RepositoryError                           Traceback (most recent call last)
<ipython-input-17-15952b6e6b71> in <module>
      9 repo = Git(uri=repo_url, gitpath=repo_dir)
     10 # fetch all commits as an iteratoir, and iterate it printing each hash
---> 11 for commit in repo.fetch():
     12     print(commit['data']['commit'])
 C:\ProgramData\Anaconda3\lib\site-packages\perceval\backend.py in fetch(self, category, **kwargs)
    125         self.client = self._init_client()
    126 
--> 127         for item in self.fetch_items(category, **kwargs):
    128             yield self.metadata(item)
    129 
C:\ProgramData\Anaconda3\lib\site-packages\perceval\backends\core\git.py in fetch_items(self, category, **kwargs)
    147             else:
    148                 commits = self.__fetch_from_repo(from_date, to_date, branches,
--> 149                                                  latest_items)
    150 
    151             for commit in commits:
C:\ProgramData\Anaconda3\lib\site-packages\perceval\backends\core\git.py in __fetch_from_repo(self, from_date, to_date, branches, latest_items)
    260         default_mode = not latest_items or not os.path.exists(self.gitpath)
    261 
--> 262         repo = self.__create_git_repository()
    263 
    264         if default_mode:
C:\ProgramData\Anaconda3\lib\site-packages\perceval\backends\core\git.py in __create_git_repository(self)
    310     def __create_git_repository(self):
    311         if not os.path.exists(self.gitpath):
--> 312             repo = GitRepository.clone(self.uri, self.gitpath)
    313         elif os.path.isdir(self.gitpath):
    314             repo = GitRepository(self.uri, self.gitpath)
C:\ProgramData\Anaconda3\lib\site-packages\perceval\backends\core\git.py in clone(cls, uri, dirpath)
    808         }
    809 
--> 810         cls._exec(cmd, env=env)
    811 
    812         logger.debug("Git %s repository cloned into %s",
C:\ProgramData\Anaconda3\lib\site-packages\perceval\backends\core\git.py in _exec(cmd, cwd, env, ignored_error_codes, encoding)
   1273             err = errs.decode(encoding, errors='surrogateescape')
   1274             cause = "git command - %s" % err
-> 1275             raise RepositoryError(cause=cause)
   1276         else:
   1277             logger.debug(errs.decode(encoding, errors='surrogateescape'))

> RepositoryError: git command - Cloning into bare repository '/tmp/perceval.git'...
fatal: unable to access 'https://github.com/chaoss/grimoirelab-perceval/': Could not resolve host: github.com

I use git in command prompt and there is no problem. I also have ping from github.com

any kind of clue would be greatly appreciated.

**Comment by sduenas** [comment] 2018-10-17 06:57
This bug is a duplicate of #399.

**Closed by sduenas** 2018-10-17 06:57 UTC
