### ISSUE TITLE
Gather the Code Review (CR) label status of patches in Gerrit

### ISSUE THREAD

**Issue by aklapper** [chaoss/grimoirelab-perceval#357] opened 2018-03-15 17:04 UTC
It looks like https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/gerrit.py does not gather CR-2, CR-1, CR0, CR+1 data from Gerrit, but only MERGED (=CR+2), ABANDONED and NEW (CR-2, CR-1, CR0, CR+1) status.

Differentiating might be nice to cover different use cases such as 
* "This patch has not received any review / feedback at all" (CR0)
* "This patch needs improvement, follow up with the developer if they plan to improve it" (CR-1)
* "This patch needs someone with CR+2 rights to merge this patch" (CR+1).

(Follow-up step would obviously be displaying the data in a column in a widget.)

**Comment by sduenas** [comment] 2018-03-15 17:21
Do you have an example of this? By the code of `gerrit` backend (https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/gerrit.py#L448), I see `perceval` is getting all the patches `open` and `closed`. Does Gerrit have other status values for those patches you're refering?

**Comment by aklapper** [comment] 2018-03-16 10:05
I was referring to the Label called "Code-Review". 
See https://gerrit-review.googlesource.com/Documentation/config-labels.html

**Comment by sduenas** [comment] 2018-03-16 17:53
Perceval is currently retrieving that field under the `approvals` entry. Here's an example taken from Mediaki's gerrit: (`Change-Id: Iacee51c31b930710f3ca59b43e01963b531b4b9f`)

```
{
   "approvals":[ ...
      {
         "type":"Code-Review",
         "grantedOn":1521218593,
         "description":"Code-Review",
         "by":{
            "username":"eevans",
            "name":"Eevans",
            "email":"eevans@wikimedia.org"
         },
         "value":"-1"
      },
      {
         "type":"Code-Review",
         "grantedOn":1521217546,
         "description":"Code-Review",
         "by":{
            "username":"jmm",
            "name":"Muehlenhoff",
            "email":"mmuhlenhoff@wikimedia.org"
         },
         "value":"1"
      },
   ...]
}
```

The problem is we're mapping these values as `NEW` in the dashboard. Check the same item in Mediawiki dashboard: https://wikimedia.biterg.io/goto/a19566c40f7396c85d020147232d470b

I think we can close this issue an open a new one either in https://github.com/chaoss/grimoirelab repository or in https://github.com/chaoss/grimoirelab-elk (which is the component that sets `NEW`and `MERGED` values`.

**Comment by aklapper** [comment] 2018-03-16 18:58
@sduenas: Uh, I see. Thanks a lot for explaining! 
Yes, we can close this ticket and re-create in a less-backend'ish repo (which one?).

(It makes sense to map that to NEW as it's neither MERGED nor ABANDONED. However for the use cases I described in the initial comment, more differentiation might sometimes be welcome - that's why I filed this, though it's low priority for me.)

**Comment by sduenas** [comment] 2018-03-22 18:58
Closing this ticket. I've opened a new one in chaoss/grimoirelab#96.

**Closed by sduenas** 2018-03-22 18:58 UTC
