### ISSUE TITLE
undocumented dependency: python3-devel

### ISSUE THREAD

**Issue by armijnhemel** [chaoss/grimoirelab-perceval#319] opened 2018-02-09 16:29 UTC
hello,

on my Fedora 26 I had to install python3-devel when installing perceval system wide. When using:

`su -c "python3 setup.py install"`

it threw this error:

Installed /usr/lib/python3.6/site-packages/urllib3-1.22-py3.6.egg
Searching for dulwich>=0.18.5
Reading https://pypi.python.org/simple/dulwich/
Downloading https://pypi.python.org/packages/3e/e9/96f83f49a02d9e5ba8e906aa6c19f1394de96f7c662bc8fe4520ceff0f7a/dulwich-0.18.6.tar.gz#md5=9d71e5ab10d889eb3fdff13f49f301bc
Best match: dulwich 0.18.6
Processing dulwich-0.18.6.tar.gz
Writing /tmp/easy_install-l4j9563z/dulwich-0.18.6/setup.cfg
Running dulwich-0.18.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-l4j9563z/dulwich-0.18.6/egg-dist-tmp-j94dqf22
dulwich/_objects.c:21:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.

And yes, I do know that pip is the recommend approach ;-)

**Comment by sduenas** [comment] 2018-02-14 12:31
This is a problem related to `dulwich` dependencies. According to its README, this can be avoided running `setup.py` with the option `--pure install` or if you're using `pip`, using the option `--global-option="--pure"`. The drawback is, that in some cases, it will reduce the performance when running `git` backend.

In any case, this should be included somehow in our documentation.

@jgbarah what should we do add this dependency? `python3-dev` is not exactly a pip package.

**Comment by jgbarah** [comment] 2018-02-15 21:49
I'm not completely sure, but I think this is due to pip not being in the latest version, and thus not installing a precompiled wheel for dulwich.

Please, try the following, and let me know if it worked (create a virtualenv, update installation tools, install perceval and all its dependencies directly from pypi). Please do that in an environment with no python3-devel available:

```
python3 -m venv /tmp/gl-perceval
source /tmp/gl-perceval/bin/activate
pip install --upgrade pip setuptools wheel
pip -no-cache-dir install perceval
```

**Comment by sduenas** [comment] 2018-03-21 09:14
@jgbarah we have checked the problem is related to dulwich and it's dependency with Python3 develpment libraries (python3-dev in Debian). I'm not sure how add this dependency.

**Comment by jgbarah** [comment] 2018-11-09 18:04
I'm adding some notes about this in the tutorial, see chaoss/grimoirelab-tutorial#50

**Comment by sduenas** [comment] 2023-10-11 15:28
I'm closing this issue because we don't use `setup.py` any more. If someone finds the same error with poetry, we will open a new issue.

**Closed by sduenas** 2023-10-11 15:28 UTC
