### ISSUE TITLE
Backend for Gerrit not respecting --from-date 

### ISSUE THREAD

**Issue by akshatmalik** [chaoss/grimoirelab-perceval#808] opened 2022-11-08 21:28 UTC
Hi, 

I have been trying to get the Gerrit backend working for a specific time period for OpenStack. However, I see that the `--from-date` parameter does not work as intended. The command I am using is ```perceval gerrit --user akshat  --json-line -o dump_file3.json --max-reviews 10 --from-date '2011-09-20'   'review.openstack.org'``` and the input it returns is as follows:

```json
    ],
    "createdOn": 1666733992,
    "hashtags": [],
    "id": "I6bb2e0822a51770b181181b49a86fb51d6dca18b",
    "lastUpdated": 1667939443,
    "number": 862646,
    "open": false,
    "owner": {
      "email": "li.zhu@windriver.com",
      "name": "Li Zhu",
      "username": "lzhu1"
    },
    "patchSets": [
      {
        "approvals": [
          {
            "by": {
              "name": "Zuul",
              "username": "zuul"
            },
            "description": "Verified",
            "grantedOn": 1666734503,
            "type": "Verified",
            "value": "-1"
          }
        ],
        "author": {
          "email": "li.zhu@windriver.com",
          "name": "Li Zhu",
          "username": "lzhu1"
        },
        "createdOn": 1666733992,
        "kind": "REWORK",
        "number": 1,
        "parents": [
          "03e953d8df762daf82356509ac71d85ff614de31"
        ],
        "ref": "refs/changes/46/862646/1",
        "revision": "aee20742e7ad684ed1c96f2efd49411333da88fc",
        "sizeDeletions": 34,
        "sizeInsertions": 94,
        "uploader": {
          "email": "li.zhu@windriver.com",
          "name": "Li Zhu",
          "username": "lzhu1"
        }
      },
```

As you can see the date created on is `1666733992` which is `October 25, 2022 9:39:52 PM` which is way off. 

Is this issue valid or am I doing something wrong?

**Comment by sduenas** [comment] 2022-11-10 16:03
Happy to have a PR with that feature too. Anything that can help to improve it, it's welcome. Take into account the backend doesn't use the Gerrit Rest API.

**Comment by sduenas** [comment] 2023-04-27 15:37
Closing this ticket as this is not a bug.

**Closed by sduenas** 2023-04-27 15:37 UTC
